"""updated relationships to fix the mapping issue

Revision ID: cafde6d50bac
Revises: 80a1f467a68d
Create Date: 2025-06-27 10:48:54.837805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafde6d50bac'
down_revision = '80a1f467a68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_order_items_product_name_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_order_items_product_id_products'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('product_name')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_product_id_products'), 'products', ['product_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_category_categories', type_='foreignkey')
        batch_op.drop_column('category')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reviews_user_id_customers', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_product_name_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_product_id_products'), 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_customer_id_customers'), 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('product_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('product_name', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_customer_id_customers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_product_name_products', 'products', ['product_name'], ['name'])
        batch_op.create_foreign_key('fk_reviews_user_id_customers', 'customers', ['user_id'], ['id'])
        batch_op.drop_column('product_id')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_products_category_categories', 'categories', ['category'], ['category_name'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_order_items_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key('fk_order_items_product_name_products', 'products', ['product_name'], ['name'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
